apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-access
  namespace: volumn-ns
  labels:
    app: redis-cluster
spec:
  ports:
    - port: 6379
      targetPort: client
      name: client
  selector:
    app: redis-cluster