apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-headless
  namespace: volumn-ns
  labels:
    app: redis-cluster
spec:
  ports:
    - port: 6379
      targetPort: client
      name: client
    - port: 16379
      targetPort: gossip
      name: gossip
  clusterIP: None
  selector:
    app: redis-cluster