apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-cluster-configmap
  namespace: volumn-ns
data:
  init.sh: |
    #!/bin/sh
    CLUSTER_CONFIG="/data/conf/nodes.conf"
    if [ -e ${CLUSTER_CONFIG} ]; then
        echo "Cluster nodes.conf is exist."
    else
        echo "Cluster nodes.conf is not exist."
        mkdir -p /data/conf
        touch ${CLUSTER_CONFIG}
    fi
    exec "$@"
  redis.conf: |+
    port 6379
    cluster-enabled yes
    cluster-config-file /data/conf/nodes.conf
    cluster-node-timeout 5000
    cluster-slave-validity-factor 0
    protected-mode no
    appendonly yes